<a href="https://colab.research.google.com/github/yijjmm/2021-AI/blob/main/210405.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. NumPy

**1-2. Why do we need NumPy?**

In [1]:
import numpy as np
import timeit

In [6]:
def sum_for_loop(n=100_000_000):
    result = 0;
    for i in range(n):
        result += i
    return result

def sum_built_in(n=100_000_000):
    return sum(range(n))

def sum_numpy(n=100_000_000):
    return np.sum(np.arange(n))

def sum_math(n=100_000_000):
    return n*(n+1)/2

In [8]:
for func in (sum_for_loop, sum_built_in, sum_numpy, sum_math):
      print(f'{func.__name__}\t{timeit.timeit(func, number=1)}')

sum_for_loop	6.9514896059999955
sum_built_in	2.2120573029999946
sum_numpy	0.1902186620000066
sum_math	4.271000022981752e-06


**1-3. ndarray**

In [12]:
a = np.array([[1, 2, 3], #[2x3]
              [4, 5, 6]], dtype=np.int32) # 2차원 행렬

print(f'type(a)   {type(a)}')
print(f'a.ndim    {a.ndim}')   # number of dimensions(=axes)
print(f'a.shape   {a.shape}')  # dimensions of the array
print(f'a.size    {a.size}')   # total number of elements
print(f'a.dtype   {a.dtype}')  # type of the elements

type(a)   <class 'numpy.ndarray'>
a.ndim    2
a.shape   (2, 3)
a.size    6
a.dtype   int32


**1-4. Array creation**

1) from a regular python list or tuple

In [ ]:
np.array([1, 2, 3, 4, 5, 6])

2) Using NumPy functions

In [13]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((2, 3, 4), dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

3) np.random

In [15]:
np.random.rand(2, 3)

array([[0.33182067, 0.14710424, 0.08496669],
       [0.31460566, 0.71679053, 0.77680067]])

In [16]:
np.random.rand(2, 3)

array([[0.2704677 , 0.64468362, 0.66353876],
       [0.15327836, 0.03201578, 0.45136192]])

<b>1-6. Basic operations</b>


Arithmetic operators on arrays apply elementwise.

In [20]:
a = np.arange(6)
b = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [18]:
a * 2

array([ 0,  2,  4,  6,  8, 10])

In [21]:
a % 2 == 0

array([ True, False,  True, False,  True, False])

Unary operations

In [22]:
a = np.random.random((3, 4))
a

array([[0.63107909, 0.10164599, 0.47537368, 0.37160226],
       [0.41737458, 0.20461333, 0.51426424, 0.81747719],
       [0.85404957, 0.85100782, 0.26239071, 0.23590005]])

In [23]:

print(f'a.sum()   {a.sum()}')
print(f'a.min()   {a.min()}')
print(f'a.max()   {a.max()}')
print(f'a.mean()  {a.mean()}')
print(f'a.std()   {a.std()}') # Z값. 표준화

a.sum()   5.736778513729498
a.min()   0.10164598509918299
a.max()   0.8540495732376182
a.mean()  0.47806487614412485
a.std()   0.25116832278382617


<b>1-7. Matrix operations</b>


Multiplication

In [25]:
a = np.arange(2*3).reshape((2, 3))
b = np.arange(3*4).reshape((3, 4))

In [26]:
# a:[2x3]  b:[3x4]  ab:[2x4]
np.matmul(a, b)

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

In [27]:
# np.matmul(a, b) : matrix product of a and b
# np.dot(a, b)    : dot product of a and b
# these give us the same results `only for 2D array`
np.dot(a, b)

array([[20, 23, 26, 29],
       [56, 68, 80, 92]])

Transpose

In [28]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
np.transpose(b)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [30]:
b.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

<b>1-8. Indexing, Slicing</b>

In [31]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
b[1, 2]

6

In [33]:
b[:, 3]

array([ 3,  7, 11])

In [34]:
b[1, :]

array([4, 5, 6, 7])

In [36]:
b[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])